### ISSUE TITLE
Revise Prework Python quizzes (create two quizzes: data structures + other)

### ISSUE THREAD

**Issue by artificialsoph** [thisismetis/dsp#161]

**Comment by kimfetti** [comment]
@artificialsoph @RobertoReif 

First Python pre-work quiz drafted and available for review here: https://www.hackerrank.com/work/tests/695058/questions

**Comment by RobertoReif** [comment]
@kimfetti this looks awesome.  A few comments:
- Who grades the manual questions? Should we make them multiple choice?
- How important do you think is the lambda question? I feel this is one of the topics many students don't really understand well, and still succeed in the BC.

**Comment by kimfetti** [comment]
Sure, I just switched the manual questions to multiple choice ones.  I also checked with Amy and sounds like we can just remove the final question about feedback.

And yes, now that I'm reviewing some of the comments about that lambda question from our spring cohort I agree it's needlessly complicated.  But I do think there should be at least one lambda question because lambdas do come up multiple times in the bootcamp.  That said, I took out the subjective lambda description question as well as the coding question.  Replaced those with one multiple choice question about lambda that is much simpler.

Let me know if you have any other comments.  I'll be moving on to the other Python quizzes now.

**Comment by kimfetti** [comment]
@artificialsoph @RobertoReif 

This item is ready for a full review.  I recommend that we replace our PreWork Python HackerRank quizzes with the following two quizzes:
- Basics with coding: https://www.hackerrank.com/work/tests/695058/questions
- Advanced (multiple choice only): https://www.hackerrank.com/work/tests/751704/questions

I also suggest that we do not attempt to teach anything via this quizzes--these should only be for testing mastery.  So the complexity blogs, cheat sheets, etc. that were included in the old Python 5.1 quiz should be moved the lessons.  I created a branch with the proposed updates to the Adv Python lesson here:
https://github.com/kimfetti/dsp/tree/adv_python_complexity_kim/lessons/python_advanced
I will submit a PR with those changes if that sounds good.

Also I suggest that we completely remove the questions in the Python 5.2 quiz (https://www.hackerrank.com/work/tests/140201/questions).  We do not currently teach the students regex and I really don't think they need to spend time figuring out how the csv library works since they will just be using pandas all the time in the course.  That is a significant change because students currently spend several hours on this quiz, so let me know what you think.

**Comment by kimfetti** [comment]
Also I am not opposed to getting students comfortable with regex during the prework -- in fact, I think we should have some regex content.  It's just that we don't currently have it, so I don't think we should test for it here.

**Comment by RobertoReif** [comment]
@kimfetti these look great to me.  A few questions:
- Do students get the solutions to the quiz?
- When are the quizzes sent to the students? 

Thanks,

Roberto

**Comment by kimfetti** [comment]
Unfortunately, scoring of each student quiz is not automatically provided to the students.  The current system is that the student would need to ask admissions for their score and then either Amy or Josh would have to download that specific student's answers and email them.  HackerRank does not provide an automated way to do this... However, HR does have an API, so it is theoretically conceivable that we could set up a chron job to automatically send scores.  I have listed that as a low priority task, however.  The other thing we could do is just provide solutions to the questions (not how the specific student did), but again, those would need to be sent manually after the student had submitted their work.

Quiz links are sent to the students in their Pre-Bootcamp Introduction email.    I think we can continue doing that for now but replace the Python and Adv Python quizzes with these and remove the Python Quick Quiz from the schedule.

**Comment by RobertoReif** [comment]
@kimfetti based on our conversation, this is good to go.  I am closing this issue!
